"""This file contains all the dictionary for higher or lower."""

higher_or_lower = {
    "1": {
        "item": "Apple iPhone 14 Pro Max",
        "price": 2199
    },

    "2": {
        "item": "Samsung Galaxy S23 Ultra",
        "price": 2148
    },

    "3": {
        "item": "Fellowes P-25S PowerShreder",
        "price": 75
    },

    "4": {
        "item": "'Best' Window Squeegee",
        "price": 11
    },

    "5": {
        "item": "Soren Sofa",
        "price": 549
    },

    "6": {
        "item": "Hugo Sofa",
        "price": 799
    },

    "7": {
        "item": "Khao Cat",
        "price": 8999
    },

    "8": {
        "item": "Desk",
        "price": 99
    },

    "9": {
        "item": "Mp3 Player",
        "price": 449
    },

    # The following was generated by AI

    "10": {
        "item": "Sony 75 Inch 4K Smart TV",
        "price": 2499
    },

    "11": {
        "item": "Apple iPod Touch 32GB",
        "price": 389
    },

    "12": {
        "item": "Apple AirPods Pro",
        "price": 439
    },

    "13": {
        "item": "ASUS ROG Zephyrus Gaming Laptop",
        "price": 3499
    },

    "14": {
        "item": "Logitech G915 Mechanical Keyboard",
        "price": 399
    },

    "15": {
        "item": "Samsung Galaxy S24 Ultra",
        "price": 2449
    },

    "16": {
        "item": "Apple Watch Series 9",
        "price": 749
    },

    "17": {
        "item": "JBL Flip 6 Bluetooth Speaker",
        "price": 189
    },

    "18": {
        "item": "DJI Mini 4 Pro Drone",
        "price": 1429
    },

    "19": {
        "item": "GoPro HERO12 Black",
        "price": 729
    },

    "20": {
        "item": "Canon EOS R6 Mark II Mirrorless Camera",
        "price": 4399
    },

    "21": {
        "item": "Apple iPad Air 64GB",
        "price": 1149
    },

    "22": {
        "item": "Meta Quest 3 VR Headset",
        "price": 929
    },

    "23": {
        "item": "Seagate Expansion 2TB External Hard Drive",
        "price": 135
    },

    "24": {
        "item": "PlayStation 5 Console",
        "price": 769
    },

    "25": {
        "item": "Fitbit Charge 6 Tracker",
        "price": 269
    },

    "26": {
        "item": "Sony WH-1000XM5 Headphones",
        "price": 549
    },

    "27": {
        "item": "Google Nest Smart Thermostat",
        "price": 329
    },

    "28": {
        "item": "iRobot Roomba j7+ Robot Vacuum",
        "price": 1499
    },

    "29": {
        "item": "Segway Ninebot Max G30 Electric Scooter",
        "price": 1299
    },

    "30": {
        "item": "Nespresso Vertuo Next Coffee Machine",
        "price": 319
    },

    "31": {
        "item": "Philips XXL Airfryer",
        "price": 429
    },

    "32": {
        "item": "NutriBullet Select Blender",
        "price": 199
    },

    "33": {
        "item": "Panasonic 27L Inverter Microwave",
        "price": 349
    },

    "34": {
        "item": "Oral-B iO Series 9 Electric Toothbrush",
        "price": 479
    },

    "35": {
        "item": "Dyson Supersonic Hair Dryer",
        "price": 649
    },

    "36": {
        "item": "Theragun Prime Massage Gun",
        "price": 499
    },

    "37": {
        "item": "Epson Home Cinema 4K Projector",
        "price": 2899
    },

    "38": {
        "item": "Sonos Arc Soundbar",
        "price": 1599
    },

    "39": {
        "item": "Google Chromecast with Google TV",
        "price": 110
    },

    "40": {
        "item": "BenQ ScreenBar LED Desk Lamp",
        "price": 229
    },

    "41": {
        "item": "Secretlab TITAN Evo Gaming Chair",
        "price": 869
    },

    "42": {
        "item": "Desky Dual Ergonomic Standing Desk",
        "price": 1049
    },

    "43": {
        "item": "Dell UltraSharp 32 Inch 4K Monitor",
        "price": 1749
    },

    "44": {
        "item": "Logitech Brio 4K Webcam",
        "price": 349
    },

    "45": {
        "item": "Shure SM7B Vocal Microphone",
        "price": 749
    },

    "46": {
        "item": "NVIDIA GeForce RTX 4080 Super Graphics Card",
        "price": 1999
    },

    "47": {
        "item": "ASUS ROG Strix Z790 Motherboard",
        "price": 689
    },

    "48": {
        "item": "Corsair RM850x Power Supply",
        "price": 259
    },

    "49": {
        "item": "NZXT H7 Flow ATX Mid-Tower PC Case",
        "price": 219
    },

    "50": {
        "item": "Corsair Vengeance 32GB DDR5 RAM Kit",
        "price": 209
    },

    "51": {
        "item": "Samsung 990 PRO 2TB NVMe SSD",
        "price": 349
    },

    "52": {
        "item": "WD Red Pro 8TB NAS Internal Hard Drive",
        "price": 489
    },

    "53": {
        "item": "ASUS ROG Rapture GT6 Wi-Fi Mesh Router",
        "price": 849
    },

    "54": {
        "item": "Netgear 8-Port Gigabit Network Switch",
        "price": 65
    },

    "55": {
        "item": "TP-Link Tapo Smart Wi-Fi Plug",
        "price": 29
    },

    "56": {
        "item": "Philips Hue White & Colour Ambiance Bulb",
        "price": 99
    },

    "57": {
        "item": "Eufy Cam 3 Wireless Security Camera",
        "price": 419
    },

    "58": {
        "item": "Ring Video Doorbell Plus",
        "price": 299
    },

    "59": {
        "item": "Schlage Encode Smart WiFi Deadbolt",
        "price": 499
    },

    "60": {
        "item": "Russell Hobbs Windsor Stainless Steel Kettle",
        "price": 89
    },

    "61": {
        "item": "Breville the Toast Select 2-Slice Toaster",
        "price": 159
    },

    "62": {
        "item": "Tiger 10-Cup Induction Rice Cooker",
        "price": 649
    },

    "63": {
        "item": "Crock-Pot 5.7L Multi-Cooker",
        "price": 179
    },

    "64": {
        "item": "Breville the Juice Fountain Cold XL",
        "price": 499
    },

    "65": {
        "item": "Magimix 5200XL Food Processor",
        "price": 999
    },

    "66": {
        "item": "Cuisinart 4-Slice Belgian Waffle Maker",
        "price": 169
    },

    "67": {
        "item": "Panasonic Automatic Bread Maker",
        "price": 399
    },

    "68": {
        "item": "Cuisinart Ice Cream and Gelato Maker",
        "price": 549
    },

    "69": {
        "item": "BioChef Arizona 8-Tray Food Dehydrator",
        "price": 329
    },

    "70": {
        "item": "FoodSaver Urban Premium Vacuum Sealer",
        "price": 249
    },

    "71": {
        "item": "Anova Precision Sous Vide Cooker",
        "price": 319
    },

    "72": {
        "item": "Instant Pot Duo Crisp 8L Pressure Cooker",
        "price": 399
    },

    "73": {
        "item": "Weber Q2600N Outdoor Gas Grill",
        "price": 699
    },

    "74": {
        "item": "Breville the Barista Express Espresso Machine",
        "price": 949
    },

    "75": {
        "item": "Nespresso Aeroccino 4 Milk Frother",
        "price": 169
    },

    "76": {
        "item": "Baratza Encore Conical Burr Coffee Grinder",
        "price": 299
    },

    "77": {
        "item": "BRITA Marella XL Water Filter Pitcher",
        "price": 45
    },

    "78": {
        "item": "SodaStream Terra Sparkling Water Maker",
        "price": 129
    },

    "79": {
        "item": "Vintec 50-Bottle Dual Zone Wine Cellar",
        "price": 2499
    },

    "80": {
        "item": "Bar Fridge 120L Stainless Steel",
        "price": 499
    },

    "81": {
        "item": "Dimplex 3.5kW Portable Air Conditioner",
        "price": 899
    },

    "82": {
        "item": "Dyson Hot+Cool AM09 Fan Heater",
        "price": 699
    },

    "83": {
        "item": "Philips Series 2000 Air Humidifier",
        "price": 279
    },

    "84": {
        "item": "Mitsubishi Electric 22L Dehumidifier",
        "price": 1099
    },

    "85": {
        "item": "Dyson Purifier Hot+Cool Formaldehyde HP09",
        "price": 1199
    },

    "86": {
        "item": "Hunter Pacific 52 Inch Ceiling Fan",
        "price": 389
    },

    "87": {
        "item": "Sunbeam 120cm Tower Fan",
        "price": 149
    },

    "88": {
        "item": "Sunbeam Sleep Perfect Queen Electric Blanket",
        "price": 199
    },

    "89": {
        "item": "Gainsborough King Heated Mattress Pad",
        "price": 249
    },

    "90": {
        "item": "Samsonite Octolite 3-Piece Luggage Set",
        "price": 1199
    },

    "91": {
        "item": "Kathmandu Litehaul 38L Backpack",
        "price": 249
    },

    "92": {
        "item": "The North Face Base Camp Duffle Bag M",
        "price": 269
    },

    "93": {
        "item": "Bellroy Hide & Seek Leather Wallet",
        "price": 149
    },

    "94": {
        "item": "Leather RFID Blocking Passport Holder",
        "price": 45
    },

    "95": {
        "item": "Nikon Monarch M7 10x42 Binoculars",
        "price": 899
    },

    "96": {
        "item": "Celestron NexStar 4SE Computerised Telescope",
        "price": 1499
    },

    "97": {
        "item": "Bushnell Tour V6 Shift Laser Rangefinder",
        "price": 649
    },

    "98": {
        "item": "Minelab Equinox 800 Metal Detector",
        "price": 1399
    },

    "99": {
        "item": "Sionyx Aurora Black Night Vision Camera",
        "price": 1299
    },

    "100": {
        "item": "Uniden 2-Way UHF Waterproof Walkie Talkie Pack",
        "price": 229
    },

    "101": {
        "item": "Garmin DriveSmart 76 GPS Navigator",
        "price": 399
    },

    "102": {
        "item": "Nextbase 622GW 4K Dash Cam",
        "price": 549
    },

    "103": {
        "item": "Anker 2-Port USB-C Car Charger 50W",
        "price": 39
    },

    "104": {
        "item": "Quad Lock Universal Car Phone Mount",
        "price": 69
    },

    "105": {
        "item": "Belkin BoostCharge Pro 3-in-1 Wireless Charger",
        "price": 229
    },

    "106": {
        "item": "Anker 737 Power Bank 24000mAh",
        "price": 249
    },

    "107": {
        "item": "Satechi Dock5 Multi-Device Charging Station",
        "price": 119
    },

    "108": {
        "item": "Apple USB-C Woven Charge Cable 2m",
        "price": 49
    },

    "109": {
        "item": "Belkin Ultra HD High Speed HDMI 2.1 Cable 2m",
        "price": 59
    },
    
    "110": {
        "item": "Yamaha Clavinova Digital Piano",
        "price": 4999
    },
    
    "111": {
        "item": "Weber Family Q Premium Gas BBQ",
        "price": 1149
    },

    "112": {
        "item": "Sennheiser HD 800 S Audiophile Headphones",
        "price": 2899
    },

    "113": {
        "item": "Breville the Oracle Touch Espresso Machine",
        "price": 3899
    },

    "114": {
        "item": "Segway Ninebot KickScooter GT2",
        "price": 4699
    },

    "115": {
        "item": "DJI Inspire 3 Professional Drone",
        "price": 9899
    },

    "116": {
        "item": "Apple MacBook Pro 16-inch M3 Max",
        "price": 6299
    },

    "117": {
        "item": "Microsoft Surface Laptop Studio 2",
        "price": 4199
    },

    "118": {
        "item": "Samsung 85-inch QN90C Neo QLED 4K TV",
        "price": 5499
    },

    "119": {
        "item": "LG 65-inch G3 OLED EVO 4K Smart TV",
        "price": 4799
    },

    "120": {
        "item": "Sony Alpha a7R V Mirrorless Camera Body",
        "price": 6699
    },

    "121": {
        "item": "Nikon Z8 Mirrorless Camera Body",
        "price": 6499
    },

    "122": {
        "item": "Fujifilm GFX 50S II Medium Format Camera",
        "price": 6299
    },

    "123": {
        "item": "Sony FE 70-200mm f2.8 GM OSS II Lens",
        "price": 4399
    },

    "124": {
        "item": "Canon RF 24-70mm f2.8 L IS USM Lens",
        "price": 3999
    },

    "125": {
        "item": "Specialized Turbo Como 4.0 Electric Bike",
        "price": 5299
    },

    "126": {
        "item": "Trek Fuel EX 7 Gen 6 Mountain Bike",
        "price": 4899
    },

    "127": {
        "item": "Thule Chariot Sport 2 Bike Trailer",
        "price": 2399
    },

    "128": {
        "item": "Tag Heuer Aquaracer Automatic Men's Watch",
        "price": 4950
    },

    "129": {
        "item": "Longines HydroConquest Automatic Watch",
        "price": 3150
    },

    "130": {
        "item": "Garmin fenix 7X Pro Sapphire Solar Watch",
        "price": 1649
    },

    "131": {
        "item": "Apple Watch Ultra 2",
        "price": 1399
    },

    "132": {
        "item": "Theragun PRO G5 Massage Gun",
        "price": 899
    },

    "133": {
        "item": "Dyson 360 Vis Nav Robot Vacuum",
        "price": 2399
    },

    "134": {
        "item": "Miele Triflex HX2 Pro Cordless Vacuum",
        "price": 1499
    },

    "135": {
        "item": "Fisher & Paykel 538L French Door Fridge",
        "price": 3299
    },

    "136": {
        "item": "Samsung 648L Family Hub Refrigerator",
        "price": 4799
    },

    "137": {
        "item": "Bosch Series 8 Front Load Washing Machine",
        "price": 1999
    },

    "138": {
        "item": "Miele 9kg Heat Pump Clothes Dryer",
        "price": 2899
    },

    "139": {
        "item": "Asko Built-In XXL Dishwasher",
        "price": 2499
    },

    "140": {
        "item": "Bose Smart Soundbar Ultra",
        "price": 1499
    },

    "141": {
        "item": "Sonos Sub Wireless Subwoofer Gen 3",
        "price": 1299
    },

    "142": {
        "item": "Genelec 8040B Studio Monitor Pair",
        "price": 3499
    },

    "143": {
        "item": "Devialet Phantom II 98dB Wireless Speaker",
        "price": 2399
    },

    "144": {
        "item": "Bang & Olufsen Beosound Explore Speaker",
        "price": 450
    },

    "145": {
        "item": "Alienware AW3423DW Curved Gaming Monitor",
        "price": 2199
    },

    "146": {
        "item": "ASUS ROG Swift 41.5-inch 4K OLED Monitor",
        "price": 2999
    },

    "147": {
        "item": "Eizo Coloredge 27-inch Hardware Monitor",
        "price": 3299
    },

    "148": {
        "item": "NVIDIA GeForce RTX 4090 Graphics Card",
        "price": 3699
    },

    "149": {
        "item": "Intel Core i9-14900KS Desktop Processor",
        "price": 1149
    },

    "150": {
        "item": "ASUS ROG Maximus Z790 Extreme Motherboard",
        "price": 1849
    },

    "151": {
        "item": "Corsair Dominator Titanium 64GB DDR5 RAM",
        "price": 549
    },

    "152": {
        "item": "Sabrent Rocket 4 Plus 8TB NVMe M.2 SSD",
        "price": 1999
    },

    "153": {
        "item": "QNAP TVS-h874 8-Bay NAS Enclosure",
        "price": 3899
    },

    "154": {
        "item": "Synology DiskStation DS1821+ 8-Bay NAS",
        "price": 1899
    },

    "155": {
        "item": "Ubiquiti UniFi Dream Machine Special Edition",
        "price": 1099
    },

    "156": {
        "item": "Netgear Orbi RBKE963 Quad-Band Mesh System",
        "price": 2999
    },

    "157": {
        "item": "EcoFlow DELTA 2 Max Portable Power Station",
        "price": 3599
    },

    "158": {
        "item": "Bluetti AC200MAX Expandable Power Station",
        "price": 3299
    },

    "159": {
        "item": "Red Paddle Co 10ft 6in Inflatable SUP Kit",
        "price": 1749
    },

    "160": {
        "item": "Hobie Mirage Passport 12 Pedalfish Kayak",
        "price": 2999
    },

    "161": {
        "item": "Zodiac Cadet 270 Aero Inflatable Boat",
        "price": 2499
    },

    "162": {
        "item": "Mercury 3.5HP 4-Stroke Outboard Motor",
        "price": 1650
    },

    "163": {
        "item": "Garmin ECHOMAP Ultra 105sv Fishfinder",
        "price": 2899
    },

    "164": {
        "item": "Gasmate Galaxy 3-Burner Built-In BBQ",
        "price": 1599
    },

    "165": {
        "item": "Gozney Dome Outdoor Multi-Fuel Pizza Oven",
        "price": 2999
    },

    "166": {
        "item": "Ooni Koda 16 Gas Powered Pizza Oven",
        "price": 1149
    },

    "167": {
        "item": "Traeger Ironwood 885 Wood Pellet Grill",
        "price": 2799
    },

    "168": {
        "item": "Kamado Joe Classic Joe Series III Grill",
        "price": 3499
    },

    "169": {
        "item": "Makita 18V 6-Piece Cordless Power Tool Kit",
        "price": 1399
    },

    "170": {
        "item": "DeWalt 18V XR 5-Piece Brushless Combo Kit",
        "price": 1249
    },

    "171": {
        "item": "Milwaukee M18 Fuel 7-Piece Power Tool Kit",
        "price": 1899
    },

    "172": {
        "item": "Husqvarna Automower 430X Robotic Mower",
        "price": 4699
    },

    "173": {
        "item": "Honda HRU196 Buffalo Pro Petrol Lawn Mower",
        "price": 1199
    },

    "174": {
        "item": "Stihl MSA 220 C-B Cordless Chainsaw Kit",
        "price": 1149
    },

    "175": {
        "item": "Karcher K7 Premium Smart Control Washer",
        "price": 1249
    },

    "176": {
        "item": "Torrot Kids Electric Motocross Bike One",
        "price": 4299
    },

    "177": {
        "item": "Intex PureSpa Greywood Deluxe Hot Tub",
        "price": 1499
    },

    "178": {
        "item": "SupaFit Seat Covers Canvas Front/Rear Set",
        "price": 750
    },

    "179": {
        "item": "Rhino-Rack Pioneer Platform Roof Rack Set",
        "price": 1350
    },

    "180": {
        "item": "Thule Motion XT XL Roof Box Black Glossy",
        "price": 1699
    },

    "181": {
        "item": "Dometic CFX3 75DZ Dual Zone Fridge Freezer",
        "price": 2049
    },

    "182": {
        "item": "Engel MT-V45F 40L Portable Fridge Freezer",
        "price": 1449
    },

    "183": {
        "item": "Bushnell Elite Tactical 3.5-21x50 Riflescope",
        "price": 2899
    },

    "184": {
        "item": "Leica Noctivid 10x42 Binoculars",
        "price": 4999
    },

    "185": {
        "item": "Swarovski ATX 25-60x85 Spotting Scope Set",
        "price": 6899
    },

    "186": {
        "item": "Black Diamond Mission 75 Backpack",
        "price": 429
    },

    "187": {
        "item": "MSR Hubba Hubba NX 2-Person Tent",
        "price": 849
    },

    "188": {
        "item": "Macpac Apollo 3-Person Geodesic Tent",
        "price": 1299
    },

    "189": {
        "item": "Sea to Summit Alpha Light Cookset 2.2",
        "price": 179
    },

    "190": {
        "item": "Exped MegaMat Duo 10 TMW Sleeping Pad",
        "price": 549
    },

    "191": {
        "item": "Therm-a-Rest NeoAir XTherm NXT Sleeping Mat",
        "price": 499
    },

    "192": {
        "item": "Kathmandu XT XT Fitzgerald Down Jacket",
        "price": 899
    },

    "193": {
        "item": "Arc'teryx Alpha SV Men's Gore-Tex Jacket",
        "price": 1549
    },

    "194": {
        "item": "Salomon Quest 4 Gore-Tex Hiking Boots",
        "price": 449
    },

    "195": {
        "item": "Lowa Renegade GTX Mid Hiking Boots",
        "price": 479
    },

    "196": {
        "item": "RM Williams Comfort Craftsman Leather Boots",
        "price": 649
    },

    "197": {
        "item": "Samsonite C-Lite Spinner 81cm Suitcase",
        "price": 799
    },

    "198": {
        "item": "Rimowa Essential Cabin Matte Black Luggage",
        "price": 1430
    },

    "199": {
        "item": "Gozer Leather 3-Seater Sofa Suite",
        "price": 3499
    },

    "200": {
        "item": "La-Z-Boy Pinnacle Leather Rocker Recliner",
        "price": 1899
    },

    "201": {
        "item": "Sleepyhead Sanctuary Queen Mattress",
        "price": 4499
    },

    "202": {
        "item": "Tempur Pro Luxe Queen Mattress",
        "price": 6299
    },

    "203": {
        "item": "Dyson Purifier Cool Autoreact Fan TP7A",
        "price": 849
    },

    "204": {
        "item": "Panasonic Nanoe X Air Conditioner 5.0kW",
        "price": 2199
    },

    "205": {
        "item": "Mitsubishi Electric 5.0kW Heat Pump",
        "price": 2499
    },

    "206": {
        "item": "Smartstone Quartz Kitchen Benchtop Slab",
        "price": 1850
    },

    "207": {
        "item": "Oliveri Santorini Double Bowl Topmount Sink",
        "price": 899
    },

    "208": {
        "item": "Hansgrohe Metris Select Kitchen Mixer Tap",
        "price": 949
    },

    "209": {
        "item": "InSinkErator Evolution 200 Waste Disposer",
        "price": 1049
    },

    "210": {
        "item": "Schweigen 90cm Silent Rangehood",
        "price": 2699
    },

    "211": {
        "item": "Smeg 90cm Portofino Pyrolytic Freestanding Cooker",
        "price": 7899
    },

    "212": {
        "item": "Neff 60cm Slide & Hide Pyrolytic Oven",
        "price": 3499
    },

    "213": {
        "item": "Miele Built-In Steam Oven",
        "price": 4299
    },

    "214": {
        "item": "Sirius 85cm Undermount Rangehood",
        "price": 1899
    },

    "215": {
        "item": "Billi Quadra Home Boiling & Chilled System",
        "price": 4599
    },

    "216": {
        "item": "Zip HydroTap G5 BC Classic Chrome",
        "price": 4899
    },

    "217": {
        "item": "Vintec 170 Bottle Multi-Zone Wine Cabinet",
        "price": 4699
    },

    "218": {
        "item": "Liebherr 307L Integrated Single Door Fridge",
        "price": 3999
    },

    "219": {
        "item": "Asko 9kg Logic Front Load Washing Machine",
        "price": 2399
    },

    "220": {
        "item": "Speed Queen 8.5kg Heavy Duty Front Washer",
        "price": 3399
    },

    "221": {
        "item": "Speed Queen 9kg Gas Clothes Dryer",
        "price": 3699
    },

    "222": {
        "item": "Sony VPL-XW5000ES 4K Laser Projector",
        "price": 8999
    },

    "223": {
        "item": "Stewart Filmscreen 110-inch Fixed Frame Screen",
        "price": 3200
    },

    "224": {
        "item": "Marantz CINEMA 40 9.4 Channel AV Receiver",
        "price": 4999
    },

    "225": {
        "item": "Denon AVC-X4800H 9.4 Channel AV Amplifier",
        "price": 3499
    },

    "226": {
        "item": "Kef LS50 Wireless II Powered Speakers Pair",
        "price": 4499
    },

    "227": {
        "item": "Klipsch Reference Premiere RP-8060FA II Pair",
        "price": 3899
    },

    "228": {
        "item": "Bowers & Wilkins 603 S3 Floorstanding Speakers",
        "price": 3699
    },

    "229": {
        "item": "Rel Acoustic T/9x Active Subwoofer",
        "price": 2299
    },

    "230": {
        "item": "Rega Planar 3 Turntable with Elys 2 MM",
        "price": 1449
    },

    "231": {
        "item": "Pro-Ject Debut PRO Turntable",
        "price": 1299
    },

    "232": {
        "item": "Focal Clear Mg Open-Back Headphones",
        "price": 2499
    },

    "233": {
        "item": "Audeze LCD-X Planar Magnetic Headphones",
        "price": 1999
    },

    "234": {
        "item": "Astor & Kern A&futura SE180 DAP",
        "price": 2399
    },

    "235": {
        "item": "Sennheiser Ambeo Soundbar Max",
        "price": 3999
    },

    "236": {
        "item": "Loewe Biline 43-inch 4K LED Smart TV",
        "price": 2199
    },

    "237": {
        "item": "Apple iPad Pro 12.9-inch 2TB Wi-Fi + Cell",
        "price": 3949
    },

    "238": {
        "item": "Wacom Cintiq Pro 27 Creative Pen Display",
        "price": 5999
    },

    "239": {
        "item": "ASUS Zenbook Pro 14 Duo OLED Laptop",
        "price": 3999
    },

    "240": {
        "item": "Lenovo ThinkPad X1 Carbon Gen 11",
        "price": 3699
    },

    "241": {
        "item": "HP Spectre x360 14-inch 2-in-1 Laptop",
        "price": 3199
    },

    "242": {
        "item": "Apple Mac Studio M2 Ultra Desktop",
        "price": 6999
    },

    "243": {
        "item": "Corsair One i500 Compact Gaming PC",
        "price": 6899
    },

    "244": {
        "item": "Eizo Radiforce 21.3-inch Medical Monitor",
        "price": 4500
    },

    "245": {
        "item": "Phidgits High Accuracy Load Cell System",
        "price": 650
    },

    "246": {
        "item": "Sony Venice 2 Cinema Camera Top Handle",
        "price": 890
    },

    "247": {
        "item": "Atomos Shogun Connect 7-inch Monitor Monitor",
        "price": 2199
    },

    "248": {
        "item": "Profoto B10X Plus OCF Flash Head",
        "price": 3699
    },

    "249": {
        "item": "Broncolor Siros 800 S WiFi Monolight",
        "price": 2999
    },

    "250": {
        "item": "Manfrotto 055 Carbon Fiber 3-Section Tripod",
        "price": 799
    },

    "251": {
        "item": "Gitzo Systematic Series 4 Carbon Tripod",
        "price": 1799
    },

    "252": {
        "item": "Sachtler Flowtech 75 MS Carbon Fiber Tripod",
        "price": 2899
    },

    "253": {
        "item": "DJI Ronin 2 Professional Gimbal Stabilizer",
        "price": 9499
    },

    "254": {
        "item": "Freefly Movi Pro Handheld Stabilizer Engine",
        "price": 8999
    },

    "255": {
        "item": "Blackmagic Design ATEM Television Studio HD",
        "price": 1749
    },

    "256": {
        "item": "Red Digital Cinema KOMODO 6K Camera Starter",
        "price": 9999
    },

    "257": {
        "item": "Sigma 24-70mm f2.8 DG DN Art Lens Sony E",
        "price": 1899
    },

    "258": {
        "item": "Tamron 35-150mm f2-2.8 Di III VXD Sony E",
        "price": 2999
    },

    "259": {
        "item": "Sony FE 50mm f1.2 GM Prime Lens",
        "price": 3299
    },

    "260": {
        "item": "Canon RF 85mm f1.2 L USM Prime Lens",
        "price": 4599
    },

    "261": {
        "item": "Nikon Nikkor Z 58mm f0.95 S Noct Lens",
        "price": 9899
    },

    "262": {
        "item": "Phase One XF Camera Electronic Cable 5m",
        "price": 350
    },

    "263": {
        "item": "Epson SureColor P906 A2 Photo Printer",
        "price": 1999
    },

    "264": {
        "item": "Canon imagePROGRAF PRO-300 A3+ Printer",
        "price": 1299
    },

    "265": {
        "item": "Blackmagic Design DaVinci Resolve Mini Panel",
        "price": 3399
    },

    "266": {
        "item": "Logic Keyboard DaVinci Resolve Mac Backlit",
        "price": 289
    },

    "267": {
        "item": "G-Technology G-RAID 2 24TB Enterprise Drive",
        "price": 2199
    },

    "268": {
        "item": "SanDisk Professional 4TB PRO-BLADE SSD",
        "price": 1049
    },

    "269": {
        "item": "LaCie 6big 24TB Thunderbolt 3 RAID Storage",
        "price": 3499
    },

    "270": {
        "item": "Glyph Production Technologies Blackbox PRO 8TB",
        "price": 649
    },

    "271": {
        "item": "Universal Audio Apollo x8 HE Audio Interface",
        "price": 4599
    },

    "272": {
        "item": "RVO Audio Fireface UFX III Interface",
        "price": 4899
    },

    "273": {
        "item": "Neumann U 87 Ai Studio Set Condenser Mic",
        "price": 5499
    },

    "274": {
        "item": "Royer Labs R-121 Ribbon Microphone",
        "price": 2499
    },

    "275": {
        "item": "Avalon Design VT-737sp Tube Channel Strip",
        "price": 6299
    },

    "276": {
        "item": "Solid State Logic Fusion Stereo Processor",
        "price": 4199
    },

    "277": {
        "item": "Empirical Labs EL8 X Distressor Compressor",
        "price": 2799
    },

    "278": {
        "item": "Barefoot Sound Footprint02 Studio Monitors Pair",
        "price": 4299
    },

    "279": {
        "item": "Adam Audio A7V Studio Monitor Pair",
        "price": 1899
    },

    "280": {
        "item": "Focal Shape 65 Studio Monitor Pair",
        "price": 2299
    },

    "281": {
        "item": "Moog Subsequent 37 Analog Synthesizer",
        "price": 3299
    },

    "282": {
        "item": "Sequential Prophet-6 6-Voice Synthesizer",
        "price": 5899
    },

    "283": {
        "item": "Nord Stage 4 88-Note Stage Keyboard",
        "price": 7499
    },

    "284": {
        "item": "Roland Fantom-8 88-Key Workstation",
        "price": 6499
    },

    "285": {
        "item": "Korg Kronos2 73-Key Music Workstation",
        "price": 5299
    },

    "286": {
        "item": "Gibson Custom Shop Les Paul Standard 1959",
        "price": 9899
    },

    "287": {
        "item": "Fender Custom Shop Stratocaster Time Machine",
        "price": 7299
    },

    "288": {
        "item": "Martin D-28 Authentic 1937 Acoustic Guitar",
        "price": 9499
    },

    "289": {
        "item": "Taylor 814ce V-Class Acoustic Electric Guitar",
        "price": 5999
    },

    "290": {
        "item": "Kemper Profiler Stage Guitar Preamp Unit",
        "price": 2799
    },

    "291": {
        "item": "Fractal Audio Axe-Fx III MKII Preamp FX",
        "price": 4399
    },

    "292": {
        "item": "Mesa Boogie Dual Rectifier 100W Tube Head",
        "price": 4899
    },

    "293": {
        "item": "Marshall 1960A Lead 300W 4x12 Cab",
        "price": 1699
    },

    "294": {
        "item": "Ampeg SVT-VR Classic Tube Bass Head",
        "price": 4299
    },

    "295": {
        "item": "Fender American Ultra Jazz Bass V",
        "price": 3699
    },

    "296": {
        "item": "DW Drums Collector's Series 4-Piece Shell",
        "price": 6999
    },

    "297": {
        "item": "Pearl Masters Maple Gum 4-Piece Drum Kit",
        "price": 4199
    },

    "298": {
        "item": "Zildjian K Custom Cymbal Box Set Pack",
        "price": 1899
    },

    "299": {
        "item": "Roland TD-50KV2 V-Drums Electronic Drum Kit",
        "price": 9699
    },

    "300": {
        "item": "Pioneer DJ DJM-A9 4-Channel DJ Mixer",
        "price": 4499
    },

    "301": {
        "item": "Pioneer DJ CDJ-3000 Professional Multi Player",
        "price": 3999
    },

    "302": {
        "item": "Technics SL-1210G Direct Drive Turntable",
        "price": 6499
    },

    "303": {
        "item": "Allen & Heath Xone:96 DJ Mixer",
        "price": 3299
    },

    "304": {
        "item": "Chauvet DJ Nimbus Dry Ice Fog Machine",
        "price": 1899
    },

    "305": {
        "item": "Martin LightJockey USB-DMX Interface Hardware",
        "price": 1500
    },

    "306": {
        "item": "MA Lighting grandMA3 onPC Command Wing",
        "price": 8499
    },

    "307": {
        "item": "Avon Inflatable Liferaft 4-Person Pack",
        "price": 3499
    },

    "308": {
        "item": "GME MT600G 406MHz GPS Emergency EPIRB",
        "price": 429
    },

    "309": {
        "item": "Lowrance HDS PRO 12 Fishfinder No Transducer",
        "price": 4799
    },

    "310": {
        "item": "Simrad NSS12 evo3S Combo Radar Screen",
        "price": 5699
    },

    "311": {
        "item": "Raymarine Quantum 2 Q24D Doppler Radar",
        "price": 3299
    },

    "312": {
        "item": "Minn Kota Terrova 80lb i-Pilot Electric Motor",
        "price": 3999
    },

    "313": {
        "item": "Motorguide Xi5 105lb 72-inch 36V Motor",
        "price": 4399
    },

    "314": {
        "item": "Juiced Bikes HyperScrambler 2 Electric Bike",
        "price": 4999
    },

    "315": {
        "item": "Super73-RX Electric Utility Motorbike",
        "price": 6499
    },

    "316": {
        "item": "Sur-Ron Light Bee X Electric Dirt Bike",
        "price": 7499
    },

    "317": {
        "item": "Ubco 2x2 Work Bike Electric Utility",
        "price": 7999
    },

    "318": {
        "item": "Segway Dirt eBike X260 Frame",
        "price": 6899
    },

    "319": {
        "item": "Stiga ST 6272 P Dual-Stage Snow Thrower",
        "price": 2899
    },

    "320": {
        "item": "Cub Cadet XT1 LT42 EFI Riding Mower",
        "price": 5999
    },

    "321": {
        "item": "John Deere S100 Lawn Tractor Mower",
        "price": 4299
    },

    "322": {
        "item": "Rover Raider 439cc 38-inch Lawn Tractor",
        "price": 3899
    },

    "323": {
        "item": "Greenworks 82V 21-inch Commercial Lawn Mower",
        "price": 1499
    },

    "324": {
        "item": "Ego Power+ Nexus Portable Power Station 3000W",
        "price": 2199
    },

    "325": {
        "item": "Tormek T-8 Custom Water Cooled Sharpening",
        "price": 1149
    },

    "326": {
        "item": "SawStop 10-inch Professional Cabinet Saw 1.75HP",
        "price": 4899
    },

    "327": {
        "item": "Laguna 14 BX Bandsaw 220V 2.5HP",
        "price": 3299
    },

    "328": {
        "item": "Nova Orion 18-inch DVR Benchtop Wood Lathe",
        "price": 3699
    },

    "329": {
        "item": "Festool Kapex KS 120 RE Miter Saw",
        "price": 2499
    },

    "330": {
        "item": "Festool Rotex RO 150 FEQ Multi-Mode Sander",
        "price": 1149
    },

    "331": {
        "item": "Mirka Deros 650CV 150mm Orbit Sander",
        "price": 999
    },

    "332": {
        "item": "Bessey K Body REVO KR 2500mm Clamp Pair",
        "price": 320
    },

    "333": {
        "item": "Snap-On 1/2-inch Drive TechAngle Torque Wrench",
        "price": 1150
    },

    "334": {
        "item": "Snap-On Heritage Series 7-Drawer Roll Cab",
        "price": 3450
    },

    "335": {
        "item": "Kincrome Evolution 6-Drawer Tool Chest Combo",
        "price": 1899
    },

    "336": {
        "item": "Teng Tools 26-Piece 1/2-inch Socket Set Metric",
        "price": 450
    },

    "337": {
        "item": "Fluke 87V Industrial Multimeter Service Kit",
        "price": 989
    },

    "338": {
        "item": "Fluke TI401 Pro Thermal Imaging Camera",
        "price": 9499
    },

    "339": {
        "item": "FLIR E8-XT Infrared Camera with Wi-Fi",
        "price": 5499
    },

    "340": {
        "item": "Teledyne LeCray WaveSurfer 100MHz Oscilloscope",
        "price": 4800
    },

    "341": {
        "item": "Rigol DS1104Z Plus 100MHz Digital Oscilloscope",
        "price": 1049
    },

    "342": {
        "item": "Formlabs Form 3+ Desktop SLA 3D Printer",
        "price": 5999
    },

    "343": {
        "item": "UltiMaker S3 Dual Extrusion 3D Printer",
        "price": 6499
    },

    "344": {
        "item": "Bambu Lab X1-Carbon Combo 3D Printer",
        "price": 2599
    },

    "345": {
        "item": "Prusa MK4 Assembled 3D Printer",
        "price": 1999
    },

    "346": {
        "item": "Flux Beambox Pro 50W CO2 Laser Cutter",
        "price": 5899
    },

    "347": {
        "item": "Glowforge Plus 3D Laser Printer Cutter",
        "price": 7499
    },

    "348": {
        "item": "Roland CAMM-1 GS-24 Desktop Vinyl Cutter",
        "price": 3199
    },

    "349": {
        "item": "Shaper Origin Handheld CNC Router System",
        "price": 4999
    },

    "350": {
        "item": "Carbide 3D Shapeoko 4 XL CNC Kit",
        "price": 3299
    },

    "351": {
        "item": "Stepcraft D.840 Desktop CNC System Kit",
        "price": 5499
    },

    "352": {
        "item": "Bernard Welder MIG Torch 400A 4.5m Air Cool",
        "price": 680
    },

    "353": {
        "item": "Lincoln Electric PowerMIG 180i Multi Welder",
        "price": 1499
    },

    "354": {
        "item": "Miller Multimatic 220 AC/DC Multi-Process",
        "price": 4999
    },

    "355": {
        "item": "Hypertherm Powermax30 XP Plasma Cutter System",
        "price": 2899
    },

    "356": {
        "item": "Cigweld WeldSkill 200 AC/DC TIG Inverter",
        "price": 1699
    },

    "357": {
        "item": "BOGE C 4 D Rotary Screw Compressor 270L",
        "price": 8999
    },

    "358": {
        "item": "Pilot Air K30 Silent Reciprocating Compressor",
        "price": 4299
    },

    "359": {
        "item": "Peerless PV25 High Volume Air Compressor",
        "price": 2199
    },

    "360": {
        "item": "Blastline Sandblasting Cabinet 220L Unit",
        "price": 1350
    },

    "361": {
        "item": "Kincrome Parts Washer 150L Benchtop",
        "price": 429
    },

    "362": {
        "item": "HBM Professional Ultrasonic Cleaner 28L",
        "price": 1149
    },

    "363": {
        "item": "Dillon XL750 Progressive Reloading Press",
        "price": 1499
    },

    "364": {
        "item": "Hornady Lock-N-Load AP Ammo Reloading Press",
        "price": 1199
    },

    "365": {
        "item": "RCBS Supreme Master Reloading Single Kit",
        "price": 799
    },

    "366": {
        "item": "Redding T-7 Turret Reloading Press Unit",
        "price": 689
    },

    "367": {
        "item": "LabRadar Doppler Bullet Velocity Chronograph",
        "price": 1199
    },

    "368": {
        "item": "Spotted Dog 120-bottle Wine Rack Modular",
        "price": 450
    },

    "369": {
        "item": "Riedel Sommeliers Bordeaux Grand Cru Glass Set",
        "price": 240
    },

    "370": {
        "item": "Zalto Denk'Art Universal Wine Glass 6-Pack",
        "price": 480
    },

    "371": {
        "item": "Coravin Timeless Six+ Wine Preservation System",
        "price": 649
    },

    "372": {
        "item": "EuroCave Wine Art Single Bottle Preserver",
        "price": 999
    },

    "373": {
        "item": "La Pavoni Professional Lusso Lever Coffee Machine",
        "price": 1999
    },

    "374": {
        "item": "Rocket Espresso Appartamento Velvet Machine",
        "price": 2899
    },

    "375": {
        "item": "Profitec Pro 600 Dual Boiler Coffee Machine",
        "price": 3699
    },

    "376": {
        "item": "Slayer Espresso Single Group Commercial Machine",
        "price": 9999
    },

    "377": {
        "item": "Mahlkonig EK43 Commercial Coffee Grinder",
        "price": 4899
    },

    "378": {
        "item": "Mazzer Mini Electronic Mod A Coffee Grinder",
        "price": 1499
    },

    "379": {
        "item": "Eureka Mignon Specialita Coffee Grinder",
        "price": 899
    },

    "380": {
        "item": "Acaia Lunar Water Resistant Espresso Scale",
        "price": 450
    },

    "381": {
        "item": "Puqpress Q2 Automatic Coffee Tamper 58mm",
        "price": 1549
    },

    "382": {
        "item": "Fellow Stagg EKG+ Electric Pour-Over Kettle",
        "price": 299
    },

    "383": {
        "item": "Ratio Eight Automatic Coffee Maker Premium",
        "price": 1249
    },

    "384": {
        "item": "Technivorm Moccamaster KBG Select Coffee Maker",
        "price": 489
    },

    "385": {
        "item": "Jura Z10 Aluminium Automatic Coffee Machine",
        "price": 4699
    },

    "386": {
        "item": "Delonghi PrimaDonna Soul Automatic Machine",
        "price": 2799
    },

    "387": {
        "item": "Philips Saeco Xelsis Suprema Espresso Maker",
        "price": 2499
    },

    "388": {
        "item": "Commercial Stainless Steel Underbench Dishwasher",
        "price": 3899
    },

    "389": {
        "item": "Skope TME1000-A ActiveCore 2-Door Display Fridge",
        "price": 4599
    },

    "390": {
        "item": "Festool CLEANTEC CT 26 AC HEPA Dust Extractor",
        "price": 1499
    },

    "391": {
        "item": "Numatic Henry Quick Cordless Vacuum Cleaner",
        "price": 699
    },

    "392": {
        "item": "Sealy Posturepedic Exquisite King Mattress",
        "price": 5499
    },

    "393": {
        "item": "Beautyrest Black K-Class Ultra Plush Mattress",
        "price": 7899
    },

    "394": {
        "item": "Ergoflex 5G HD Memory Foam Queen Mattress",
        "price": 1399
    },

    "395": {
        "item": "Auping Essential Designer Bed Frame Queen",
        "price": 3200
    },

    "396": {
        "item": "Natuzzi Edition C005 Fabric Recliner Chair",
        "price": 2199
    },

    "397": {
        "item": "Stressless Mayfair Leather Recliner & Stool",
        "price": 3899
    },

    "398": {
        "item": "Herman Miller Aeron Ergonomic Office Chair",
        "price": 2399
    },

    "399": {
        "item": "Steelcase Gesture Task Office Chair Black",
        "price": 1899
    },

    "400": {
        "item": "Humanscale Freedom Headrest Task Chair",
        "price": 2199
    },

    "401": {
        "item": "AA Alkaline Batteries 4-Pack",
        "price": 8
    },

    "402": {
        "item": "Stainless Steel Pocket Ruler 15cm",
        "price": 5
    },

    "403": {
        "item": "Microfibre Cleaning Cloths 3-Pack",
        "price": 7
    },

    "404": {
        "item": "Ceramic Coffee Mug 350ml Matte Black",
        "price": 12
    },

    "405": {
        "item": "A4 Refill Pad 200 Pages Lined",
        "price": 6
    },

    "406": {
        "item": "USB 2.0 Flash Drive 32GB",
        "price": 15
    },

    "407": {
        "item": "Plastic Storage Bin with Lid 10L",
        "price": 11
    },

    "408": {
        "item": "Spiral Notebook A5 120 Pages",
        "price": 5
    },

    "409": {
        "item": "Desktop Tape Dispenser with 1 Roll",
        "price": 9
    },

    "410": {
        "item": "Retractable Utility Knife with Spare Blades",
        "price": 14
    },

    "411": {
        "item": "Sticky Notes 76x76mm Yellow 3-Pack",
        "price": 6
    },

    "412": {
        "item": "Heavy Duty Fridge Magnets 10-Pack",
        "price": 13
    },

    "413": {
        "item": "Kitchen Scissors Stainless Steel",
        "price": 16
    },

    "414": {
        "item": "Digital Kitchen Timer Magnetic Back",
        "price": 19
    },

    "415": {
        "item": "Woven Cotton Coasters 4-Pack",
        "price": 10
    },

    "416": {
        "item": "LED Keychain Torch Compact",
        "price": 7
    },

    "417": {
        "item": "Double Sided Mounting Tape 2m",
        "price": 12
    },

    "418": {
        "item": "Fluorescent Highlighter Pens 4-Pack Assorted",
        "price": 5
    },

    "419": {
        "item": "Paper Clips 28mm Vinyl Coated 200-Pack",
        "price": 4
    },

    "420": {
        "item": "Stainless Steel Water Bottle 750ml",
        "price": 25
    },

    "421": {
        "item": "BPA-Free Plastic Lunch Box 1.2L",
        "price": 14
    },

    "422": {
        "item": "Silicone Ice Cube Tray with Lid",
        "price": 9
    },

    "423": {
        "item": "Non-Stick Frying Pan 20cm",
        "price": 29
    },

    "424": {
        "item": "Wooden Wooden Cooking Spoons 3-Piece Set",
        "price": 8
    },

    "425": {
        "item": "Porcelain Cereal Bowl White",
        "price": 6
    },

    "426": {
        "item": "Glass Measuring Jug 500ml",
        "price": 15
    },

    "427": {
        "item": "Handheld Milk Frother Battery Operated",
        "price": 18
    },

    "428": {
        "item": "Cotton Tea Towels 2-Pack Waffle Weave",
        "price": 11
    },

    "429": {
        "item": "Dish Drying Rack Chrome Finished",
        "price": 34
    },

    "430": {
        "item": "Wall Mounted Key Hook Organiser",
        "price": 22
    },

    "431": {
        "item": "Scented Candle Soy Wax Vanilla 150g",
        "price": 19
    },

    "432": {
        "item": "Photo Frame 4x6 Inch Black Wood",
        "price": 10
    },

    "433": {
        "item": "Fabric Mouse Pad with Gel Wrist Rest",
        "price": 17
    },

    "434": {
        "item": "3.5mm Aux Audio Cable 1m Gold Plated",
        "price": 12
    },

    "435": {
        "item": "Micro USB Charging Cable 1.5m",
        "price": 9
    },

    "436": {
        "item": "Cable Organiser Ties Hook and Loop 20-Pack",
        "price": 8
    },

    "437": {
        "item": "Adjustable Smartphone Desk Stand Plastic",
        "price": 15
    },

    "438": {
        "item": "Webcam Cover Slider Ultra Thin 3-Pack",
        "price": 6
    },

    "439": {
        "item": "Screen Cleaning Spray with Microfibre Cloth",
        "price": 14
    },

    "440": {
        "item": "AAA Alkaline Batteries 4-Pack",
        "price": 8
    },

    "441": {
        "item": "CR2032 Coin Cell Batteries 5-Pack",
        "price": 11
    },

    "442": {
        "item": "4-Way Power Board Overload Protection 1m",
        "price": 19
    },

    "443": {
        "item": "Travel Adapter Plug NZ to US/EU/UK",
        "price": 24
    },

    "444": {
        "item": "Digital Luggage Scale Handheld 50kg Max",
        "price": 16
    },

    "445": {
        "item": "Combination Padlock 3-Digit Brass",
        "price": 13
    },

    "446": {
        "item": "Playing Cards Waterproof Plastic Deck",
        "price": 9
    },

    "447": {
        "item": "Stainless Steel Multi-Tool Pocket Card",
        "price": 7
    },

    "448": {
        "item": "Paracord Survival Bracelet with Whistle",
        "price": 12
    },

    "449": {
        "item": "Emergency Poncho Lightweight Waterproof",
        "price": 4
    },

    "450": {
        "item": "First Aid Kit Compact 50-Piece",
        "price": 29
    },

    "451": {
        "item": "Pet Hair Remover Roller Reusable",
        "price": 15
    },

    "452": {
        "item": "Collapsible Pet Travel Bowl Silicone",
        "price": 8
    },

    "453": {
        "item": "Tennis Balls 3-Pack Tube",
        "price": 11
    },

    "454": {
        "item": "Skipping Rope Adjustable Speed Cable",
        "price": 16
    },

    "455": {
        "item": "Resistance Bands Set of 3 Loop Bands",
        "price": 22
    },

    "456": {
        "item": "Yoga Mat Strap Carrying Sling Cotton",
        "price": 9
    },

    "457": {
        "item": "Microfibre Sports Towel Quick Dry Medium",
        "price": 17
    },

    "458": {
        "item": "Waterproof Phone Pouch Dry Bag Case",
        "price": 13
    },

    "459": {
        "item": "Bicycle Bell Classic Aluminium Ring",
        "price": 7
    },

    "460": {
        "item": "Bike Tyre Lever Matrix 3-Pack",
        "price": 6
    },

    "461": {
        "item": "Puncture Repair Kit with Patches and Glue",
        "price": 10
    },

    "462": {
        "item": "LED Bike Light Set Front and Rear",
        "price": 24
    },

    "463": {
        "item": "Reflective Safety Vest High Visibility",
        "price": 8
    },

    "464": {
        "item": "Ergonomic Foam Earplugs 10-Pair Pack",
        "price": 9
    },

    "465": {
        "item": "Sleep Mask Contoured 3D Blindfold",
        "price": 14
    },

    "466": {
        "item": "Lip Balm SPF 15 Coconut Flavoured",
        "price": 5
    },

    "467": {
        "item": "Travel Size Toiletry Bottles 4-Pack Silicone",
        "price": 16
    },

    "468": {
        "item": "Bamboo Toothbrush Medium Bristles 4-Pack",
        "price": 12
    },

    "469": {
        "item": "Dental Floss Mint Waxed 50m",
        "price": 4
    },

    "470": {
        "item": "Hand Sanitiser Gel 60ml Clip-On",
        "price": 5
    },

    "471": {
        "item": "Pocket Tissues 3-Ply 10-Pack",
        "price": 6
    },

    "472": {
        "item": "Wet Wipes Antibacterial 40-Pack",
        "price": 7
    },

    "473": {
        "item": "Lint Roller 60-Sheets with Handle",
        "price": 8
    },

    "474": {
        "item": "Safety Pins Assorted Sizes 50-Pack",
        "price": 4
    },

    "475": {
        "item": "Sewing Thread Kit 10 Spools Assorted Colors",
        "price": 11
    },

    "476": {
        "item": "Measuring Tape Soft Fabric 1.5m",
        "price": 3
    },

    "477": {
        "item": "Mini Stapler with 1000 Staples Standard",
        "price": 7
    },

    "478": {
        "item": "Hole Punch Single Metal Handheld",
        "price": 9
    },

    "479": {
        "item": "Push Pins Clear Plastic Map Tacks 100-Pack",
        "price": 5
    },

    "480": {
        "item": "Rubber Bands Size 18 100g Bag",
        "price": 4
    },

    "481": {
        "item": "Document Wallet Plastic A4 Button Closure",
        "price": 3
    },

    "482": {
        "item": "Clipboards A4 Hardboard Top Profile Clip",
        "price": 8
    },

    "483": {
        "item": "Permanent Marker Black Fine Chisel Tip",
        "price": 5
    },

    "484": {
        "item": "Whiteboard Markers 4-Pack Assorted Bullet",
        "price": 11
    },

    "485": {
        "item": "Magnetic Whiteboard Eraser Lightweight",
        "price": 6
    },

    "486": {
        "item": "Mechanical Pencils 0.5mm 3-Pack with Leads",
        "price": 9
    },

    "487": {
        "item": "Erasers Large Neon Rubber 3-Pack",
        "price": 4
    },

    "488": {
        "item": "Pencil Sharpener Dual Hole with Receptacle",
        "price": 6
    },

    "489": {
        "item": "Stainless Steel Tweezers Slant Tip",
        "price": 10
    },

    "490": {
        "item": "Nail Clippers Carbon Steel Large",
        "price": 7
    },

    "491": {
        "item": "Emery Boards Nail Files 10-Pack Pack",
        "price": 5
    },

    "492": {
        "item": "Pocket Mirror Dual Magnification Compact",
        "price": 12
    },

    "493": {
        "item": "Hair Elastics Black No-Metal 30-Pack",
        "price": 6
    },

    "494": {
        "item": "Bobby Pins Black 50mm Slide 60-Pack",
        "price": 5
    },

    "495": {
        "item": "Pocket Comb Fine and Coarse Tooth Plastic",
        "price": 3
    },

    "496": {
        "item": "Shoelaces Round Athletic Black 120cm Pair",
        "price": 8
    },

    "497": {
        "item": "Instant Shoe Shine Sponge Clear Fluid",
        "price": 9
    },

    "498": {
        "item": "Luggage Tag Plastic ID Strap Window Label",
        "price": 4
    },

    "499": {
        "item": "Key Ring Split Rings Assorted 20-Pack",
        "price": 6
    },
    
    "500": {
        "item": "Desk Mat Protective Blotter Pad Smooth",
        "price": 24
    }

}

